travis:
  secure:
    BINSTAR_TOKEN: CQ4PvJljz+o5WRLX3Cp6sKpxT6FPIXNMoNZioiYi1j/SDkf+yMlsxsNSK4uag9NFF2SEOgtr3QoHL2sr+O5+hsxC1IKL9SuQFOQ0yXhn3tDicB91fY7Pl1+tWoGzw0O74dQeo4IlHwRkndKnLpfLhaF44YMu+cKWbcsL1ww3nTlJns3ZC0S7X4YlssHjIeqvfp+NLWYg29X4LTvukHwng8ewIPocY1JGRw9plTmC6TofUYcJAao1FxSAENzZSeWJq/UvfRTWKvL8WARgLYHz2UNi7GMPP97vdw/1Bdh8Uemy70IYDjneIt+6nUvy4z0R1O0NbmTfhvQv0Rlg0YhGXFpPNBi4pmPqgIUrHZjvANU64TPjFmMVo6+MvQtyajrMSkW6h8CP0SM2kG1d8SOSXplgb5UIXoX+pBeoKPamcEDSrH5jICNAzEopiDirXAjeGHQ9KxBCj6kDMzg6cuxrhFG4M7Tm1WxijQPrAunu3zQWzNCTbag1EP4ieyrXktaVt2mrFKKGSXpVyeebBcYwJG1rqrdp4hVZ0EJmKwW17Wij6mNP+NJXikrsCIvGFY5jFKEtIz5sw5Dc8HWQLUqY/nRMDpWgTBKYZwEy5Hp9Gu7yb2f6rq4qzBF4VO2NizsMdTbXpVSka94EOSbVSWgFIUm7jSbcEkdfJDSZsdW0rdY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
